// SPDX-License-Identifier: Apache-2.0 OR MIT
pragma solidity ^0.8.36;

import {ServiceRewardsActor, Share} from "../../src/ServiceRewardsActor.sol";
import {Epoch} from "../../src/lib/Epoch.sol";
import {FixedU18} from "../../src/lib/FixedU18.sol";

/// @dev Differential test harness: inherits ServiceRewardsActor, exposing the internal
///      _computeShares (largest-remainder share allocation) via a public wrapper for the
///      differential tests to call the on-chain implementation directly.
///      Difference from test/halmos/ComputeSharesHarness.sol: this harness uses a public wrapper
///      (normal EVM calls, not halmos symbolic execution); the owner is generated by SRATestBase's
///      Safe helpers, so it deploys normally under forge test.
contract DifferentialSharesHarness is ServiceRewardsActor {
    constructor(
        address o1,
        address o2,
        uint64 epochsPerQuarter,
        uint64 postPeriod,
        uint64 verificationWindow,
        uint64 activationEpoch,
        uint256 minLot,
        uint256 priceBand
    )
        ServiceRewardsActor(
            o1,
            o2,
            Epoch.wrap(epochsPerQuarter),
            Epoch.wrap(postPeriod),
            Epoch.wrap(verificationWindow),
            Epoch.wrap(activationEpoch),
            minLot,
            priceBand
        )
    {}

    function computeShares(address[] memory wallets, uint256[] memory usds, uint256 count, uint256 total)
        public
        pure
        returns (Share[] memory)
    {
        // Public test entry keeps uint256 (the postVolume input form); wrap to FixedU18 (values are
        // already 18-decimal USD, no scaling) so the production _computeShares runs type-checked.
        Share[] memory shares = new Share[](usds.length);
        for (uint256 i = 0; i < usds.length; i++) {
            shares[i] = Share({wallet: wallets[i], share: FixedU18.wrap(usds[i])});
        }
        _computeShares(shares, count, FixedU18.wrap(total));
        return shares;
    }
}
