// SPDX-License-Identifier: Apache-2.0 OR MIT
pragma solidity ^0.8.36;

// Differential tests: on-chain _computeShares output vs the Python reference model
// (DifferentialCases.shareCases, generated by tools/differential_model.py)
//
// FIP-0118 (FIPs#1275): FilecoinPayVolume is a single USD total — the PRICE_BAND differential
// (bandCases) is obsolete (band check removed), and the aggregation differential
// (aggCases) collapses to a simple sum, so both are replaced by a few hand-written
// aggregation cases below. The largest-remainder share differential is kept.

import {ServiceRewardsActor, Share} from "../../src/ServiceRewardsActor.sol";
import {Epoch} from "../../src/lib/Epoch.sol";
import {SRATestBase} from "../SRATestBase.sol";
import {FixedU18} from "../../src/lib/FixedU18.sol";
import {DifferentialCases} from "./DifferentialCases.sol";
import {DifferentialSharesHarness} from "./DifferentialSharesHarness.sol";

contract DifferentialSharesTest is SRATestBase {
    DifferentialSharesHarness internal harness;

    function setUp() public virtual override {
        super.setUp();
        harness = new DifferentialSharesHarness(
            owner1,
            owner2,
            EPOCHS_PER_QUARTER,
            POST_PERIOD,
            VERIFICATION_WINDOW,
            SRA_CANCEL_HOLD,
            ACTIVATION_EPOCH,
            MIN_LOT,
            PRICE_BAND
        );
    }

    // ------------------------------------------------------------------------
    // 1. Largest-remainder share allocation: on-chain _computeShares output == Python reference model expectation
    // ------------------------------------------------------------------------

    function test_Diff_Share_MaxRemainder_AllCases() public view {
        DifferentialCases.ShareCase[] memory cases = DifferentialCases.shareCases();
        for (uint256 i = 0; i < cases.length; i++) {
            uint256[] memory usds = cases[i].usds;
            uint256 total;
            for (uint256 j = 0; j < usds.length; j++) {
                total += usds[j];
            }
            address[] memory wallets = _wallets(usds.length);
            Share[] memory shares = harness.computeShares(wallets, usds, usds.length, total);

            assertEq(shares.length, cases[i].expected.length, _msg("share", i, "length"));
            for (uint256 j = 0; j < shares.length; j++) {
                assertEq(FixedU18.unwrap(shares[j].share), cases[i].expected[j], _msg("share", i, "value"));
            }
        }
    }

    /// @dev Boundary: total == 0 must not silently produce a wrong allocation. In production
    ///      submitShares guards total == 0 with an early return (no-op); calling _computeShares
    ///      directly with total == 0 hits the FixedU18 remainder `% totalUsd` → division-by-zero
    ///      Panic(0x12) — a safe failure (no silent wrong values). Locks the behavior boundary.
    function test_Diff_Share_TotalZero_Reverts() public {
        address[] memory wallets = new address[](1);
        wallets[0] = address(0x1);
        uint256[] memory usds = new uint256[](1);
        usds[0] = 100e18;
        vm.expectRevert(); // Panic(0x12): remainder % totalUsd with totalUsd == 0
        harness.computeShares(wallets, usds, 1, 0);
    }

    // ------------------------------------------------------------------------
    // 2. FilecoinPayVolume aggregation (FIPs#1275: single USD total — the aggregate is a plain sum;
    //    hand-written cases exercise the contract's sum)
    // ------------------------------------------------------------------------

    /// Single orchestrator: aggregatedFilecoinPayVolume == its posted USD total.
    function test_Diff_Aggregate_SingleOrch() public {
        ServiceRewardsActor s = _newSra();
        address a = makeAddr("agg-single");
        _admitOn(s, a);
        vm.roll(_qEnd(0) + 1);
        vm.prank(a);
        s.postVolume(0, FixedU18.wrap(350e18));

        _rollTo(_qVerifyEnd(0) + 1); // post-binding
        assertEq(FixedU18.unwrap(s.aggregatedFilecoinPayVolume(0)), 350e18);
    }

    /// Multiple orchestrators: aggregatedFilecoinPayVolume == Σ posted USD totals.
    function test_Diff_Aggregate_MultiOrch() public {
        ServiceRewardsActor s = _newSra();
        uint256 expected;
        for (uint256 k = 0; k < 3; k++) {
            address orch = makeAddr(string.concat("agg-", vm.toString(k)));
            _admitOn(s, orch);
            vm.roll(_qEnd(0) + 1);
            uint256 usd = 100e18 * (k + 1);
            vm.prank(orch);
            s.postVolume(0, FixedU18.wrap(usd));
            expected += usd;
        }

        _rollTo(_qVerifyEnd(0) + 1);
        assertEq(FixedU18.unwrap(s.aggregatedFilecoinPayVolume(0)), expected);
    }

    // ------------------------------------------------------------------------
    // helpers
    // ------------------------------------------------------------------------

    function _wallets(uint256 n) internal pure returns (address[] memory w) {
        w = new address[](n);
        for (uint256 i = 0; i < n; i++) {
            w[i] = address(uint160(i + 1)); // non-zero addresses; share assertions only inspect values
        }
    }

    function _newSra() internal returns (ServiceRewardsActor s) {
        s = new ServiceRewardsActor(
            owner1,
            owner2,
            Epoch.wrap(EPOCHS_PER_QUARTER),
            Epoch.wrap(POST_PERIOD),
            Epoch.wrap(VERIFICATION_WINDOW),
            Epoch.wrap(SRA_CANCEL_HOLD),
            Epoch.wrap(ACTIVATION_EPOCH),
            MIN_LOT,
            PRICE_BAND
        );
    }

    /// @dev Runs the governance three-phase admit on the given SRA instance (the base _admit always operates on the sra instance).
    function _admitOn(ServiceRewardsActor s, address orch) internal {
        vm.prank(owner1);
        s.admit(orch);
        vm.prank(owner2);
        s.admit(orch);
        vm.roll(block.number + SRA_CANCEL_HOLD);
        s.admit(orch); // third call (permissionless) completes execution
    }

    function _msg(string memory kind, uint256 i, string memory what) internal pure returns (string memory) {
        return string.concat("differential ", kind, " case ", vm.toString(i), ": ", what);
    }
}
