[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
cache_path = 'cache'
solc = "0.8.36"
via_ir = false
optimizer = true
optimizer_runs = 2000
bytecode_hash = "none"

# For dependencies
remappings = [
    'forge-std/=lib/forge-std/src/',
    'fvm-solidity/=lib/fvm-solidity/src/',
    '@safe/=lib/safe-smart-account/contracts/',
]

[lint]
severity = ["high", "med", "low", "info", "gas", "code-size"]
exclude_lints = [
    "incorrect-shift",
    "mixed-case-function",
    "multi-contract-file",
    "unsafe-typecast",
    "unwrapped-modifier-logic",
]
