#!/usr/bin/env bash
# Snapshot every ERC-7201 namespaced storage struct in src/ and the OpenZeppelin proxy storage this repo
# depends on, so that CI can flag layout changes on upgradeable contracts.
#
# Solstice keeps no linear state variables (everything lives in @custom:storage-location structs at fixed
# slots), so `forge inspect <Contract> storageLayout` is empty and cannot catch a breaking change. This script
# captures the source of truth instead: each namespaced struct body and its slot constant.
#
# Usage:
#   tools/storage-layout-snapshot.sh            # regenerate storage-layout/namespaced.txt
#   tools/storage-layout-snapshot.sh --check    # fail if the committed snapshot is stale
#
# Review rule (see docs/UPGRADE.md): a diff in this file on an upgrade is allowed only if it appends new fields
# to the end of an existing struct or adds a brand-new namespace. Reordering, removing, retyping or inserting a
# field, or changing a slot constant, is a storage-breaking change and must not ship behind an existing proxy.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT=storage-layout/namespaced.txt
mkdir -p storage-layout

snapshot() {
    echo "# Generated by tools/storage-layout-snapshot.sh. Do not edit by hand."
    echo
    # Files that declare a namespaced struct, plus the OZ proxy storage we inherit.
    local files
    files=$(grep -rl '@custom:storage-location' src lib/openzeppelin-contracts/contracts/proxy/utils/Initializable.sol | sort)
    for f in $files; do
        echo "## $f"
        # Slot constants next to the struct (Solstice libs hardcode them; OZ derives them the same way).
        grep -E 'bytes32 (private |internal )?constant [A-Z_]+(_SLOT|_STORAGE) =' "$f" | sed 's/^[[:space:]]*/slot: /' || true
        # Every struct in the file (the namespaced root and the structs nested in it), through the closing brace.
        awk '
            /^[[:space:]]*struct [A-Za-z0-9_]+ \{/ { capture = 1 }
            capture { print }
            capture && /^[[:space:]]*}[[:space:]]*$/ { capture = 0; print "" }
        ' "$f" | sed 's#[[:space:]]*//.*$##; s/^[[:space:]]*//' | grep -vE '^(\*|/\*|$)' | sed -E 's/^([^s}])/    \1/' || true
        echo
    done
}

if [[ "${1:-}" == "--check" ]]; then
    if ! diff -u "$OUT" <(snapshot); then
        echo
        echo "storage layout snapshot is stale or a namespaced struct changed; run tools/storage-layout-snapshot.sh" >&2
        exit 1
    fi
    echo "storage layout snapshot is up to date"
else
    snapshot > "$OUT"
    echo "wrote $OUT"
fi
