#!/usr/bin/env bash
# Snapshot every storage struct that lives behind an ERC-7201 namespace in src/ (plus the OpenZeppelin
# Initializable storage this repo inherits) and check that changes are upgrade-safe.
#
# Solstice keeps no linear state variables (everything lives in @custom:storage-location structs at fixed
# slots), so `forge inspect <Contract> storageLayout` is empty and cannot catch a breaking change. This script
# captures the source of truth instead: each struct body and its slot constant.
#
# Usage:
#   tools/storage-layout-snapshot.sh                    # regenerate storage-layout/namespaced.txt
#   tools/storage-layout-snapshot.sh --check            # fail if the committed snapshot is stale
#   tools/storage-layout-snapshot.sh --compat <git-ref> # fail if the layout is not upgrade-safe vs <git-ref>
#
# Upgrade-safe (--compat passes) means: every slot constant present at <git-ref> is unchanged, every struct
# present at <git-ref> still starts with the same fields in the same order with the same types, and only new
# fields at the end of a struct or brand-new structs/namespaces were added. Anything else is a storage-breaking
# change and cannot ship behind a live proxy without a migration (see docs/UPGRADE.md).
set -euo pipefail

cd "$(dirname "$0")/.."
OUT=storage-layout/namespaced.txt
mkdir -p storage-layout

snapshot() {
    echo "# Generated by tools/storage-layout-snapshot.sh. Do not edit by hand."
    echo
    local files
    files=$(grep -rl '@custom:storage-location' src lib/openzeppelin-contracts/contracts/proxy/utils/Initializable.sol | sort)
    for f in $files; do
        echo "## $f"
        grep -E 'bytes32 (private |internal )?constant [A-Z_]+(_SLOT|_STORAGE) =' "$f" | sed 's/^[[:space:]]*/slot: /' || true
        awk '
            /^[[:space:]]*struct [A-Za-z0-9_]+ \{/ { capture = 1 }
            capture { print }
            capture && /^[[:space:]]*}[[:space:]]*$/ { capture = 0; print "" }
        ' "$f" | sed 's#[[:space:]]*//.*$##; s/^[[:space:]]*//' | grep -vE '^(\*|/\*|$)' | sed -E 's/^([^s}])/    \1/' || true
        echo
    done
}

compat() {
    local base_ref=$1
    local base_file
    base_file=$(mktemp)
    if ! git show "$base_ref:$OUT" > "$base_file" 2>/dev/null; then
        echo "no snapshot at $base_ref:$OUT; nothing to compare against"
        rm -f "$base_file"
        return 0
    fi
    local new_file rc
    new_file=$(mktemp)
    snapshot > "$new_file"
    python3 - "$base_file" "$new_file" <<'EOF'
import re, sys

def parse(text):
    slots, structs = {}, {}
    struct, fields = None, None
    for line in text.splitlines():
        m = re.match(r'slot: bytes32 (?:private |internal )?constant ([A-Z_]+) = (0x[0-9a-fA-F]+);', line)
        if m:
            slots[m.group(1)] = m.group(2).lower()
            continue
        m = re.match(r'struct ([A-Za-z0-9_]+) \{', line)
        if m:
            struct, fields = m.group(1), []
            continue
        if struct is not None:
            if line.strip() == '}':
                structs[struct] = fields
                struct, fields = None, None
            elif line.strip():
                fields.append(line.strip().rstrip(';'))
    return slots, structs

base_slots, base_structs = parse(open(sys.argv[1]).read())
new_slots, new_structs = parse(open(sys.argv[2]).read())
errors = []
for name, value in base_slots.items():
    if name not in new_slots:
        errors.append(f'slot constant {name} was removed')
    elif new_slots[name] != value:
        errors.append(f'slot constant {name} changed from {value} to {new_slots[name]}')
for name, fields in base_structs.items():
    if name not in new_structs:
        errors.append(f'struct {name} was removed')
        continue
    new = new_structs[name]
    if new[:len(fields)] != fields:
        for i, (old_f, new_f) in enumerate(zip(fields, new)):
            if old_f != new_f:
                errors.append(f'struct {name} field {i} changed: "{old_f}" -> "{new_f}"')
                break
        else:
            errors.append(f'struct {name} lost fields: {fields[len(new):]}')
if errors:
    print('storage layout is NOT upgrade-safe relative to base:')
    for e in errors:
        print('  -', e)
    sys.exit(1)
added = [n for n in new_structs if n not in base_structs]
grown = [n for n in new_structs if n in base_structs and len(new_structs[n]) > len(base_structs[n])]
print('storage layout is upgrade-safe relative to base' + (f' (new structs: {added})' if added else '') + (f' (appended fields in: {grown})' if grown else ''))
EOF
    rc=$?
    rm -f "$base_file" "$new_file"
    return $rc
}

case "${1:-}" in
    --check)
        if ! diff -u "$OUT" <(snapshot); then
            echo
            echo "storage layout snapshot is stale; run tools/storage-layout-snapshot.sh and commit the result" >&2
            exit 1
        fi
        echo "storage layout snapshot is up to date"
        ;;
    --compat)
        compat "${2:?usage: --compat <git-ref>}"
        ;;
    "")
        snapshot > "$OUT"
        echo "wrote $OUT"
        ;;
    *)
        echo "unknown option: $1" >&2
        exit 2
        ;;
esac
